# Generated by Django 3.0.3 on 2020-03-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0002_comment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(),
        ),
    ]
