# Generated by Django 3.0.3 on 2020-03-27 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0004_auto_20200325_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='messages',
        ),
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='message_app.Message'),
        ),
    ]
